# Generated by Django 4.0.4 on 2022-05-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
