# Generated by Django 4.0.4 on 2022-05-31 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_alter_articles_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.articles')),
            ],
        ),
    ]
