# Generated by Django 4.0.4 on 2022-05-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='is_searching_for',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='price',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
